export const indianColleges = [
  // IITs
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "Indian Institute of Technology Guwahati (IIT Guwahati)",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
  "Indian Institute of Technology Indore (IIT Indore)",
  "Indian Institute of Technology Varanasi (IIT BHU)",
  "Indian Institute of Technology Dhanbad (IIT ISM)",
  "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",
  "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
  "Indian Institute of Technology Jodhpur (IIT Jodhpur)",
  "Indian Institute of Technology Patna (IIT Patna)",
  "Indian Institute of Technology Ropar (IIT Ropar)",
  "Indian Institute of Technology Mandi (IIT Mandi)",
  "Indian Institute of Technology Tirupati (IIT Tirupati)",
  "Indian Institute of Technology Palakkad (IIT Palakkad)",
  "Indian Institute of Technology Goa (IIT Goa)",
  "Indian Institute of Technology Dharwad (IIT Dharwad)",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Jammu (IIT Jammu)",

  // NITs
  "National Institute of Technology Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology Surathkal (NITK Surathkal)",
  "National Institute of Technology Warangal (NIT Warangal)",
  "National Institute of Technology Calicut (NIT Calicut)",
  "National Institute of Technology Rourkela (NIT Rourkela)",
  "Motilal Nehru National Institute of Technology Allahabad (MNNIT Allahabad)",
  "Malaviya National Institute of Technology Jaipur (MNIT Jaipur)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "Visvesvaraya National Institute of Technology Nagpur (VNIT Nagpur)",
  "National Institute of Technology Durgapur (NIT Durgapur)",
  "National Institute of Technology Silchar (NIT Silchar)",
  "Dr B R Ambedkar National Institute of Technology Jalandhar (NIT Jalandhar)",
  "National Institute of Technology Meghalaya (NIT Meghalaya)",
  "Maulana Azad National Institute of Technology Bhopal (MANIT Bhopal)",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Agartala (NIT Agartala)",
  "National Institute of Technology Goa (NIT Goa)",
  "National Institute of Technology Jamshedpur (NIT Jamshedpur)",
  "National Institute of Technology Patna (NIT Patna)",
  "National Institute of Technology Hamirpur (NIT Hamirpur)",
  "National Institute of Technology Puducherry (NIT Puducherry)",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "National Institute of Technology Uttarakhand (NIT Uttarakhand)",
  "National Institute of Technology Delhi (NIT Delhi)",

  // IIITs
  "International Institute of Information Technology Hyderabad (IIIT Hyderabad)",
  "International Institute of Information Technology Bangalore (IIIT Bangalore)",
  "Indraprastha Institute of Information Technology Delhi (IIIT Delhi)",
  "Indian Institute of Information Technology Allahabad (IIIT Allahabad)",
  "Indian Institute of Information Technology Gwalior (IIIT Gwalior)",
  "Indian Institute of Information Technology Jabalpur (IIIT Jabalpur)",
  "Indian Institute of Information Technology Kancheepuram (IIIT Kancheepuram)",
  "Indian Institute of Information Technology Guwahati (IIIT Guwahati)",
  "Indian Institute of Information Technology Pune (IIIT Pune)",
  "Indian Institute of Information Technology Vadodara (IIIT Vadodara)",
  "Indian Institute of Information Technology Kota (IIIT Kota)",
  "Indian Institute of Information Technology Sri City (IIIT Sri City)",
  "Indian Institute of Information Technology Lucknow (IIIT Lucknow)",

  // BITS
  "Birla Institute of Technology and Science Pilani (BITS Pilani)",
  "BITS Pilani - Goa Campus",
  "BITS Pilani - Hyderabad Campus",
  "Birla Institute of Technology Mesra (BIT Mesra)",

  // Top Private & Tech Universities
  "Vellore Institute of Technology (VIT)",
  "Manipal Institute of Technology",
  "SRM Institute of Science and Technology (SRM)",
  "Thapar Institute of Engineering and Technology",
  "Amrita Vishwa Vidyapeetham",
  "Kalinga Institute of Industrial Technology Bhubaneswar (KIIT)",
  "PSG College of Technology Coimbatore",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Jadavpur University",
  "College of Engineering Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI Mumbai)",
  "PEC University of Technology",
  "MS Ramaiah Institute of Technology",
  "RV College of Engineering (RVCE)",
  "BMS College of Engineering (BMSCE)",
  "PES University",
  "Shiv Nadar University (SNU)",
  "Amity University",
  "Lovely Professional University (LPU)",
  "Chandigarh University",
  "Galgotias University",
  "Sathyabama Institute of Science and Technology",
  "SASTRA Deemed University",
  "Jaypee Institute of Information Technology (JIIT)",
  "Nirma University",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DAIICT)",
  "Pune Institute of Computer Technology (PICT)",
  "Sardar Patel Institute of Technology (SPIT)",
  "KJ Somaiya College of Engineering",
  "Dwarkadas J. Sanghvi College of Engineering",
  "Maharashtra Institute of Technology (MIT WPU)",
  "Techno India University",
  "Heritage Institute of Technology",
  "Haldia Institute of Technology",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "Jawaharlal Nehru University (JNU)",
  "Anna University",
  "SSN College of Engineering",
  "Madras Institute of Technology (MIT Chennai)",
  "Visvesvaraya Technological University (VTU)",
  "Graphic Era University",
  "Chitkara University",
  "Banasthali Vidyapith",
  "Nitte Meenakshi Institute of Technology",
  "Christ University",
  "Maharaja Surajmal Institute of Technology (MSIT)",
  "Maharaja Agrasen Institute of Technology (MAIT)",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
  "Siksha 'O' Anusandhan",

  // IIMs & Business Schools
  "Indian Institute of Management Ahmedabad (IIM Ahmedabad)",
  "Indian Institute of Management Bangalore (IIM Bangalore)",
  "Indian Institute of Management Calcutta (IIM Calcutta)",
  "Indian Institute of Management Lucknow (IIM Lucknow)",
  "Indian Institute of Management Indore (IIM Indore)",
  "Indian Institute of Management Kozhikode (IIM Kozhikode)",
  "Indian School of Business (ISB)",
  "XLRI - Xavier School of Management",
  "SPJIMR",
  "Faculty of Management Studies Delhi (FMS Delhi)",
  "MDI Gurgaon",
  "Symbiosis Institute of Business Management (SIBM)",

  // Other Prominent Institutes
  "Osmania University",
  "Andhra University",
  "University of Hyderabad",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "University of Mumbai",
  "Savitribai Phule Pune University",
  "Gujarat Technological University (GTU)",
  "Panjab University",
  "Kurukshetra University",
  "M.S. University of Baroda",
  "University of Delhi",
  "Guru Gobind Singh Indraprastha University (GGSIPU)",
  "Dr. A.P.J. Abdul Kalam Technical University (AKTU)",
  "Rajasthan Technical University (RTU)",
];
